version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - selenium-net

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-net
    shm_size: 2g

networks:
  selenium-net:

volumes:
  jenkins_home: